[tool.poetry]
name = "scanapi"
version = "2.5.0"
description = "Automated Testing and Documentation for your REST API"
authors = ["Camila Maia <cmaiacd@gmail.com>"]
license = "MIT"
readme = "README.md"

repository = "https://github.com/scanapi/scanapi"
homepage = "https://scanapi.dev/"
keywords = ["python", "scanapi", "tests", "end2end", "endtoend", "integration tests", "json", "apis", "api rest"]

[tool.poetry.scripts]
scanapi = "scanapi:main"

[tool.poetry.dependencies]
python = ">=3.6.2,<4.0.0"
click = "7.1.2"
jinja2 = "2.11.3"
pyyaml = "5.4"
requests = "2.26.0"
appdirs = "^1.4.4"
curlify2 = "^1.0.1"

[tool.poetry.dev-dependencies]
codecov = "2.1.7"
pytest = "6.1.0"
pytest-cov = "2.10.0"
pytest-freezegun = "0.4.1"
pytest-mock = "3.2.0"
requests-mock = "1.8.0"
black = "19.10b0"
sphinx = "3.1.2"
sphinx_rtd_theme = "^0.5.0"
pre-commit = "2.6.0"
isort = "^5.5.3"
bandit = "^1.6.2"
pytest-it = "^0.1.4"
flake8 = "3.8.4"
mypy = "^0.910"
types-requests = "^2.25.1"
types-PyYAML = "^5.4.3"
types-setuptools = "^57.0.0"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true

[tool.pytest.ini_options]
addopts="--it"

[build-system]
requires = ["poetry>=1.0.9",  "poetry-dynamic-versioning"]
build-backend = "poetry.masonry.api"
